[package]
name = "score"
version = "0.0.1"
description = "Example Rust library."
license = "MIT"
authors = [ "herman@hermanradtke.com" ]

[lib]
name = "score"
crate-type = ["dylib"]

[dependencies]
libc = "0.1.7"
